apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wema
  name: wema
spec:
  replicas: 7
  selector:
    matchLabels:
      app: wema
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wema
    spec:
      containers:
      - image: maxoba/kubernginx:4.0.0
        name: kubernginx
        resources: {}
status: {}
