apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wema
  name: wema
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
        - image: maxoba/kubenginx:4.0.0
          name: kubernetes
          resources: {}
status: {}
